# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull hepsw/cvmfs-cms

install:
 - sudo docker build -t cms-l1t-offline/cms-l1t-analysis -f ci/Dockerfile .

script:
  - sudo docker run -t -v $PWD:/analysis --privileged=true cms-l1t-offline/cms-l1t-analysis
cache: apt
