version: 0.0.1
name: 'Offline Met Studies'

input:
  files:
      # Single Muons
      -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/306125sm_def/180117_161529/0000/L1Ntuple_*.root
      -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/SingleMuon/306125sm_def/180117_161529/0001/L1Ntuple_*.root
      # Zero Bias
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/ZeroBias/306125zb_def/180117_161553/0000/L1Ntuple_*.root

  sample:
    name: Data
    title: 2017 Data
  trigger:
    # name: ZeroBias
    # title: Zero Bias
    name: SM
    title: Single Muon
  pileup_file: ""
  run_number: 306125

analysis:
  do_fit: True
  pu_type: 0PU24,25PU49,50PU
  pu_bins: [0,25,50,999]
  analyzers:
     - cmsl1t.analyzers.offline_met_analyzer
  modifiers: []
  progress_bar:
    report_every: 1000

output:
  template:
     - output/offline_met_studies
     - "{date}_Fill-{run_number}_{sample_name}_{trigger_name}"
