version: 1
name: 'Jet Met MC Studies'

input:
  ntuple_map_file: config/ntuple_content_mc.yaml
  files:
      # QCD MC
       - 7x7check.root
  sample:
    name: MC
    title: TDR
  trigger:
    name: histPFJet
    title: ttbar+QCD
  pileup_file: ""
  run_number:

analysis:
  load_trees:
    - genTree
    - p2Upgrade

  do_fit: True
  pu_type: 0PU24,25PU49,50PU
  pu_bins: [0,25,50,999]
  thresholds:
    HT:           [120, 200, 320, 460]
    HT_Emu:       [120, 200, 320, 460]
    METBE:        [80, 100, 120]
    METBE_Emu:    [80, 100, 120]
    METHF:        [80, 100, 120]
    METHF_Emu:    [80, 100, 120]
    JetET_BE:     [35, 90, 120, 180]
    JetET_BE_Emu: [35, 90, 120, 180]
    JetET_HF:     [35, 90, 120, 180]
    JetET_HF_Emu: [35, 90, 120, 180]

  analyzers:
     jetMet_analyzer:
       module: cmsl1t.analyzers.jetMet_analyzer
  producers:
    l1Jets:
      module: cmsl1t.producers.jets
      inputs:
        - L1PhaseIPFJet_phaseIPFJetEt
        - L1PhaseIPFJet_phaseIPFJetEta
        - L1PhaseIPFJet_phaseIPFJetPhi
      jetType: L1
      filter: null
      outputs:
        - l1Jets
    l1EmuJets:
      module: cmsl1t.producers.jets
      inputs:
        - L1AK4PFJet_ak4PFJetEt
        - L1AK4PFJet_ak4PFJetEta
        - L1AK4PFJet_ak4PFJetPhi
      jetType: L1
      filter: null
      outputs:
        - l1EmuJets

    goodGenJets:
      module: cmsl1t.producers.jets
      inputs:
        - Generator_jetPt
        - Generator_jetEta
        - Generator_jetPhi
      jetType: Gen
      outputs:
        - goodGenJets

output:
  template:
     - output/constant_rate_turnons
     - "{date}_{sample_name}_{trigger_name}"
