version: 0.0.1
name: 'Jet Met Rate vs Pileup'

input:
  files:
      # Zero Bias
       -  root://eoscms.cern.ch//eos/cms//store/group/dpg_trigger/comm_trigger/L1Trigger/bundocka/cmsl1t/zbMedPU_9.root
  sample:
    name: Data
    title: 2017 Data
  trigger:
    name: zbMed
    title: Zero Bias
  pileup_file: ""
  run_number:
  lumi_json: "https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions17/13TeV/PromptReco/Cert_294927-306462_13TeV_PromptReco_Collisions17_JSON.txt"

analysis:
  load_trees:
    - event
    - emuCaloTowers
    - emuUpgrade
    - upgrade
    - recoTree
  do_fit: True
  pu_type: 0PU24,25PU49,50PU
  pu_bins: [0,25,50,999]
  thresholds:
    HT:           [120, 200, 320]
    HT_Emu:       [120, 200, 320]
    METBE:        [80, 100, 120]
    METBE_Emu:    [80, 100, 120]
    METHF:        [80, 100, 120]
    METHF_Emu:    [80, 100, 120]
    JetET_BE:     [35, 90, 120]
    JetET_BE_Emu: [35, 90, 120]
    JetET_HF:     [35, 90, 120]
    JetET_HF_Emu: [35, 90, 120]

  analyzers:
     jetMet_analyzer:
       module: cmsl1t.analyzers.HW_Emu_jetMet_rates
  producers: []

output:
  template:
     - output/zb_rates
     - "{date}_{run_number}_{sample_name}_{trigger_name}"
