version: 1
name: 'Study Tower 20 MET'

input:
  files:
    # - data/L1Ntuple_*.root
    - test/data/*.root
  sample:
    name: Data
    title: 2016 Data
  trigger:
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 276243

analysis:
  load_trees:
    - event
    - upgrade
    - caloTowers
    - emuCaloTowers
    - emuUpgrade
    - jetReco
    - metFilterReco
    - recoTree
    - muonReco
  do_fit: False
  pu_type: 0PU12,13PU19,20PU
  pu_bins: 0,13,20,999
  analyzers:
    study_tower28_met:
      module: cmsl1t.analyzers.study_tower28_met
  producers:
    l1MetNot28:
      module: cmsl1t.recalc.met.l1MetNot28
        inputs:
          - caloTowers
        outputs:
          - l1MetNot28
    l1MetNot28HF:
      module: cmsl1t.recalc.met.l1MetNot28HF
        inputs:
          - caloTowers
        outputs:
          - l1MetNot28

output:
  # template is a list here that is joined (os.path.join) in the config parser
  template:
     - output/study_tower28_met
     - "{date}_{sample_name}_run-{run_number}_{trigger_name}"
