version: 1
name: 'Weekly Checks'

input:
  files:
      # Single Muons
      # -   root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Collision2017-wRECO-l1t-integration-v96p27/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27__SingleMuon/170818_102121/000*/L1Ntuple_*.root
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/SingleMuon/Fill*/Collision2017-wRECO-l1t-integration-v96p27_CaloMode/SingleMuon/crab_Collision2017-wRECO-l1t-integration-v96p27_CaloMode__SingleMuon/*/0000/L1Ntuple_*root
      # Zero Bias
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/ZeroBias/Fill6*/Collision2017-noRECO-l1t-integration-96p27_NoPUS/ZeroBias/crab_Collision2017-noRECO-l1t-integration-96p27_NoPUS__ZeroBias_Run2017C/*/0000/L1Ntuple_*root
      # -  root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/safarzad/2017/ZeroBias/Collision2017-noRECO-l1t-integration-96p20/ZeroBias/crab_Collision2017-noRECO-l1t-integration-96p20__ZeroBias_Run2017C/170726_094745/0000/*root
      - test/data/*.root
  sample:
    name: Data
    title: 2017 Data
  trigger:
    # name: ZeroBias
    # title: Zero Bias
    name: SingleMu
    title: Single Muon
  pileup_file: ""
  run_number: 6XXX

analysis:
  load_trees:
    - event
    - upgrade
    - emuCaloTowers
    - emuUpgrade
    - jetReco
    - metFilterReco
    - recoTree
  do_fit: True
  pu_type: 0PU12,13PU19,20PU
  pu_bins: [0,13,20,999]
  thresholds:
    HT:           [120, 200, 320]
    HT_Emu:       [120, 200, 320]
    METBE:        [80, 100, 120]
    METBE_Emu:    [80, 100, 120]
    METHF:        [80, 100, 120]
    METHF_Emu:    [80, 100, 120]
    JetET_BE:     [35, 90, 120]
    JetET_BE_Emu: [35, 90, 120]
    JetET_HF:     [35, 90, 120]
    JetET_HF_Emu: [35, 90, 120]
  analyzers:
      weekly_analyzer:
        module: cmsl1t.analyzers.weekly_analyzer
      jetMet_analyzer:
        module: cmsl1t.analyzers.jetMet_analyzer
  producers:
    l1Sums:
      module: cmsl1t.producers.l1sums
      inputs:
        - L1Upgrade_sumBx
        - L1Upgrade_sumType
        - L1Upgrade_sumEt
        - L1Upgrade_sumPhi
      outputs:
        - l1Sums
    l1EmuSums:
      module: cmsl1t.producers.l1sums
      inputs:
        - emu_L1Upgrade_sumBx
        - emu_L1Upgrade_sumType
        - emu_L1Upgrade_sumEt
        - emu_L1Upgrade_sumPhi
      outputs:
        - l1EmuSums
    goodPFJets:
      module: cmsl1t.producers.jets
      inputs:
        - Jet_et
        - Jet_eta
        - Jet_phi
        - Jet_etCorr
        - Jet_cemef
        - Jet_chef
        - Jet_cMult
        - Jet_mef
        - Jet_muMult
        - Jet_nemef
        - Jet_nhef
        - Jet_nMult
      jetType: PF
      filter: cmsl1t.filters.jets.pfJetFilter
      outputs:
        - goodPFJets
    caloJets:
      module: cmsl1t.producers.jets
      inputs:
        - Jet_caloEt
        - Jet_caloEta
        - Jet_caloPhi
        - Jet_caloEtCorr
      jetType: Calo
      filter: null
      outputs:
        - caloJets
    l1Jets:
      module: cmsl1t.producers.jets
      inputs:
        - L1Upgrade_jetEt
        - L1Upgrade_jetEta
        - L1Upgrade_jetPhi
        - L1Upgrade_jetBx
      jetType: L1
      filter: null
      outputs:
        - l1Jets
    l1EmuJets:
      module: cmsl1t.producers.jets
      inputs:
        - emu_L1Upgrade_jetEt
        - emu_L1Upgrade_jetEta
        - emu_L1Upgrade_jetPhi
        - emu_L1Upgrade_jetBx
      jetType: L1
      filter: null
      outputs:
        - l1EmuJets

output:
  template:
     - output/weekly_checks
     - "{date}_Fill-{run_number}_{sample_name}_{trigger_name}"
